apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiod
  namespace: istio-system
spec:
  profile: default
  meshConfig:
    accessLogFile: /dev/stdout
    enableAutoMtls: true
  components:
    pilot:
      k8s:
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
        nodeSelector:
          node-type: on-demand
  values:
    global:
      proxy:
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
